### ISSUE TITLE
Add `v0.3.0` documentation `README.md`

### ISSUE THREAD

**Issue by lakscastro** [lakscastro/shared-storage#12]
## Samples

Documentation should have a collection of examples to allow easy usage

## Cookbooks

Explain what is happening behind the Dart code

**Comment by hpoul** [comment]
Any progress on 3.0.0? Are you still working on this plugin? thanks.

**Comment by lakscastro** [comment]
no, the development of this package is currently frozen

**Comment by lakscastro** [comment]
Closed a time ago by #42.

See releases.
