### ISSUE TITLE
List files in a chosen uri

### ISSUE THREAD

**Issue by Mostafakhaled999** [lakscastro/shared-storage#15]
Thanks for the awesome package great work.

1- I have some data saved like pics, audios and pdfs, I need to list and read all the files in a chosen URI.
2- How to create a directory, I want to know mime type for the directory?

Thanks. @lakscastro

**Comment by lakscastro** [comment]
Hey! Thanks for using the package :)

These features are currently available only on `master` branch (not published yet) I'll try to give a shot today but I can't promise to publish up to tomorrow

**Comment by lakscastro** [comment]
Closing due lack of activity. Feel free to re-open, or create a new issue.
