### ISSUE TITLE
testing example on Android12+

### ISSUE THREAD

**Issue by aplicatii-romanesti** [lakscastro/shared-storage#16]
gives an apparently well known error:
"[Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]]" -as seen also: https://stackoverflow.com/questions/70333565/targeting-s-version-31-and-above-requires-that-an-explicit-value-for-android)
Solution is simple, add: `android:exported="true"` in the AndroidManifest.xml

**Comment by lakscastro** [comment]
Gotcha, thx for reporting

**Comment by aplicatii-romanesti** [comment]
closed by PR#17
