### ISSUE TITLE
What if persisted document directory get deleted by the user?

### ISSUE THREAD

**Issue by dhaval-k-simformsolutions** [lakscastro/shared-storage#20]
**Describe the bug**
In my App, I have selected one directory to store files and then I deleted that directory manually so next time I'll get the URL when I call `persistedUriPermissions` but when I try to add files under that directory it throws the error as directory does not exists which is correct. So What is the solution/workaround for this using which we can identify whether the persisted URL path exists or not?

Even I am not able to find the real path from the Document Tree URL.

**To Reproduce**
1. OpenDocument Tree
2. Save the file on the above path using `createDocumentFile`.
3.  Delete the Directory to which we gave access in step 1 manually. 
4. Next time when we try to store a file we will check any URL available or not in `persistedUriPermissions` and we will find that url in the list.
5. When we try to store the file using the persistedUriPermissions item it will throw an error as Directory does not exist. 

**Expected behavior**
I want a solution/workaround using either We can check the persisted Uri exists or not or I want real path using which I can manually check the directory exists or not.

**Comment by dhaval-k-simformsolutions** [comment]
@lakscastro  Do you have any plan to fix the above issue and release the latest version or is there any way using which I can fix it by doing a change in the native android of this plugin?

**Comment by lakscastro** [comment]
I guess it's currently fixed, cause in this next release you'll can use `canRead` or `exists` API to see if a Uri is available/valid

**Comment by dhaval-k-simformsolutions** [comment]
@lakscastro Thanks for the quick reply, Can you please share some code examples using which we can check the same? And the function/method `canRead` or `Exists` are available there in the master branch of the repository?

**Comment by lakscastro** [comment]
yep, they are defined here:

https://github.com/lakscastro/shared-storage/blob/master/lib/src/storage_access_framework/saf.dart#L186-L193

```dart
/// Verify if a given [uri] exists
Future<bool?> exists(Uri uri) async {
  const kExists = 'exists';

  const kUri = 'uri';

  final args = <String, String>{kUri: '$uri'};

  return kDocumentFileChannel.invokeMethod<bool>(kExists, args);
}
```

The usage is just a simple: `exists(uri)` where the `uri` is the one you mentioned in the description which you got by calling `persistedUriPermissions` same applies for `canRead`

**Comment by dhaval-k-simformsolutions** [comment]
@lakscastro  Thanks for your answer It's worked for me. You can simply mark the check box again this in you PR so other people can simple find the solution and issue marked as done on that PR.

**Comment by dhaval-k-simformsolutions** [comment]
@lakscastro  When do you have a plan to release the new version 0.3.0 on pub.dev?

**Comment by lakscastro** [comment]
For now what is missing are these bugs on Android 9 and lower, and [this](https://stackoverflow.com/questions/71996022/how-do-i-open-a-child-document-of-a-granted-uri-using-action-view)

**Comment by dhaval-k-simformsolutions** [comment]
Till we fix or found the solution to that issue we can release the already fixed issues as we have fixed many in this release.

And one more thing I want to know that on which branch do we have the latest changes master or 0.3.0?

**Comment by lakscastro** [comment]
Yeah, we can do it as well, thx for the tip. Guess May 8 is ok, since I need to write the docs of the entire API and I can work on this only on weekends

The `v0.3.0` branch is currently with the latest changes, but I guess next release will be implemented entirely on master instead of a separated branch

**Comment by dhaval-k-simformsolutions** [comment]
Sounds good to me. Also currently Google rejects the apps if we do not use the storage permission wisely so I think your release will be very helpful to all flutter users and the number of open issues counts will decrease as well...  For the same enough questions are also available on the StackOverflow and one package is also there [SAF](https://pub.dev/packages/saf) using it we can get the permission of the doc directory but there is no way to create a file on permitted uri.

**Comment by dhaval-k-simformsolutions** [comment]
> #22

For now, I have applied the workaround this is, I am checking whether the same name file exists or not if available then I delete the same file first and then create the new one so ideally, it seems like we have over-right the existing file. Not the ideal solution User can go forward with this workaround for now.

**Comment by lakscastro** [comment]
@all-contributors please add @dhaval-k-simformsolutions for bug

**Comment by lakscastro** [comment]
@all-contributors please add @dhaval-k-simformsolutions for ideas

**Comment by dhaval-k-simformsolutions** [comment]
> Yeah, we can do it as well, thx for the tip. Guess May 8 is ok, since I need to write the docs of the entire API and I can work on this only on weekends
> 
> The `v0.3.0` branch is currently with the latest changes, but I guess next release (0.4.0) will be implemented entirely on master instead of a separated branch

@lakscastro  Do we have any plan to release the next version with issues that we have already fixed in nearby days?

**Comment by lakscastro** [comment]
Yes, I'm late, but guess in a few days we have a new release

Also, take a look at [`lakscastro.github.io/shared-storage`](https://lakscastro.github.io/shared-storage) since the docs are going to be larger I splited into a website to avoid a super sized `README.md`

Some parts are missing yet but the hardest part for me is done (move docs to outside of GitHub and keep the versioning) I never did this before, so any feedback would be helpful

**Comment by lakscastro** [comment]
Since the original issue was solved, I'll close this fow now, any question let me know.
