### ISSUE TITLE
Add support for `FileProvider` API

### ISSUE THREAD

**Issue by lakscastro** [lakscastro/shared-storage#3]
### API's

Add implementation to allow us handle [`FileProvider` Android API](https://developer.android.com/reference/androidx/core/content/FileProvider)

- [ ] [`Context#getExternalMediaDirs`](https://developer.android.com/reference/android/content/Context.html#getExternalMediaDirs())
- [ ] [`FileProvider.getUriForFile`](https://developer.android.com/reference/androidx/core/content/FileProvider#getUriForFile(android.content.Context,%20java.lang.String,%20java.io.File))

**Comment by LaksCastro** [comment]
Archived. Currently working on SAF (Storage Access Framework, #4) this issue no longer will be implemented in a near release.
